### PR TITLE
Refactor dc

### PR DESCRIPTION
**Pull request by snoglobe**
DONT REPEAT YOURSELF !!!!!!!!

I made this PR because I don't know if my changes break anything - I need y'all to look and make sure it's OK

### CODE REVIEW

**Comment by snoglobe** [comment]
Ignore the weird commits; I had to roll back because I forgot to change the commit message lol
The one you want to pay attention to is "Refactor driver control slightly; less repeating code"

**Comment by recursiveforte** [comment]
I'll take a look in a bit!

**Comment by recursiveforte** [comment]
Ty!

**Comment by snowsign** [comment]
whoops, ignore that

**Pull request merged**
